apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: epicenter-postgres-pvc
  namespace: epicenter
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 50Gi
  